<a href="https://colab.research.google.com/github/kkumarisfdc/Kiran-s_Portfolio/blob/main/Pandas_for_Genomics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {
    "gRNA":["g1","g2","g3","g4","g5","g6","g7","g8","g9","g10"],
    "Gene":["TP53","TP53","BRCA1", "BRCA1", "EGFR","EGFR","MYC","MYC","KRAS","KRAS"],
    "Efficiency":[0.82,0.75,0.65,0.92,0.95,0.78,0.88,0.72,0.97,0.81]
}

In [ ]:
df=pd.DataFrame(data)
df

  gRNA   Gene  Efficiency
0   g1   TP53        0.82
1   g2   TP53        0.75
2   g3  BRCA1        0.65
3   g4  BRCA1        0.92
4   g5   EGFR        0.95
5   g6   EGFR        0.78
6   g7    MYC        0.88
7   g8    MYC        0.72
8   g9   KRAS        0.97
9  g10   KRAS        0.81

In [ ]:
df.head()

  gRNA   Gene  Efficiency
0   g1   TP53        0.82
1   g2   TP53        0.75
2   g3  BRCA1        0.65
3   g4  BRCA1        0.92
4   g5   EGFR        0.95

In [ ]:
df["Gene"]

0     TP53
1     TP53
2    BRCA1
3    BRCA1
4     EGFR
5     EGFR
6      MYC
7      MYC
8     KRAS
9     KRAS
Name: Gene, dtype: object

In [ ]:
high_eff = df[df["Efficiency"]>0.80]
high_eff

  gRNA   Gene  Efficiency
0   g1   TP53        0.82
3   g4  BRCA1        0.92
4   g5   EGFR        0.95
6   g7    MYC        0.88
8   g9   KRAS        0.97
9  g10   KRAS        0.81

In [ ]:
threshold = df["Efficiency"].quantile(0.95)
print(threshold)

0.961

In [ ]:
top_guides = df[
    df["Efficiency"] >= threshold

]
top_guides

  gRNA  Gene  Efficiency
8   g9  KRAS        0.97

In [ ]:
df.sort_values(
    by="Efficiency",
    ascending=False
)

  gRNA   Gene  Efficiency
8   g9   KRAS        0.97
4   g5   EGFR        0.95
3   g4  BRCA1        0.92
6   g7    MYC        0.88
0   g1   TP53        0.82
9  g10   KRAS        0.81
5   g6   EGFR        0.78
1   g2   TP53        0.75
7   g8    MYC        0.72
2   g3  BRCA1        0.65

In [ ]:
gene_summary  = df.groupby(
    "Gene"
)["Efficiency"].mean()
gene_summary

Gene
BRCA1    0.785
EGFR     0.865
KRAS     0.890
MYC      0.800
TP53     0.785
Name: Efficiency, dtype: float64

In [ ]:
df.groupby(
    "Gene"
)["Efficiency"].agg(["mean","max","min"])

        mean   max   min
Gene
BRCA1  0.785  0.92  0.65
EGFR   0.865  0.95  0.78
KRAS   0.890  0.97  0.81
MYC    0.800  0.88  0.72
TP53   0.785  0.82  0.75

In [ ]:
gene_info = pd.DataFrame(
    {
        "Gene":["TP53","BRCA1","EGFR","MYC","KRAS"],
        "Chromosome":[17,17,17,8,12]
    }
)
gene_info

    Gene  Chromosome
0   TP53          17
1  BRCA1          17
2   EGFR          17
3    MYC           8
4   KRAS          12

In [ ]:
merged = pd.merge(
    df,
    gene_info,
    on="Gene"
)

merged

  gRNA   Gene  Efficiency  Chromosome
0   g1   TP53        0.82          17
1   g2   TP53        0.75          17
2   g3  BRCA1        0.65          17
3   g4  BRCA1        0.92          17
4   g5   EGFR        0.95          17
5   g6   EGFR        0.78          17
6   g7    MYC        0.88           8
7   g8    MYC        0.72           8
8   g9   KRAS        0.97          12
9  g10   KRAS        0.81          12